Update download link to v2fly.
v2fly/alpinelinux-install-v2ray pull request #3
Opened 2020-12-28 06:03 UTC by elvisw

现在`v2fly`这边预编译了更多平台，但是我不知道如何获得`arch -s`命令在其他平台的输出。

2020-12-28 06:05 UTC, kslr commented
你可以参考fhs

2020-12-28 06:49 UTC, elvisw commented
下载没问题了，但是已经确认 #2 的BUG。本人水平有限没法修复，看能有其他人来处理不

2020-12-29 06:10 UTC, elvisw commented
> 下载没问题了，但是已经确认 #2 的BUG。本人水平有限没法修复，看能有其他人来处理不

测试了一下，#2 应该是修复了，现在应该可以合并了 @kslr

2020-12-29 08:08 UTC, IceCodeNew requested changes

2020-12-29 08:08 UTC, IceCodeNew commented on install-release.sh
> +        MACHINE='arm32-v7a'
这里存在的问题是没有考虑到如果 CPU features 不支持 VFP 的可能。
相关的处理可以参考 https://github.com/v2fly/fhs-install-v2ray/commit/ecc831a3411d9f54e3f8c2a46ec3dc7a9d64a012

这个改进我很早就放进 dev 分支了，但是没有人响应来帮忙测试。

2020-12-29 08:23 UTC, elvisw commented on install-release.sh
> +        MACHINE='arm32-v7a'
这个改进需要加上吗？
我手上只有aacrh64的设备，看其他人有没有能够测试的设备。

2020-12-29 08:31 UTC, IceCodeNew commented on install-release.sh
> +        MACHINE='arm32-v7a'
我的建议是加上，这个情况挺普遍的。
但是是否先测试过一遍、如何测试就是你的判断了~

2020-12-29 08:47 UTC, IceCodeNew approved these changes

2020-12-29 08:50 UTC, IceCodeNew commented
这个项目我之前没有参与过，所以我并没有写权限。
虽然理解我被请求审阅这个 PR 的缘由，但我无法合并你的 PR。

2020-12-29 08:52 UTC, elvisw commented
> 这个项目我之前没有参与过，所以我并没有写权限。
> 虽然理解我被请求审阅这个 PR 的缘由，但我无法合并你的 PR。

没事，那就先放着吧。我先用着我fork的脚本

2020-12-29 16:48 UTC, merged

2020-12-29 16:52 UTC, kslr commented
Thanks for your work